name = "GeoStatsSolvers"
uuid = "50e95529-e670-4fa6-84ad-e28f686cc091"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
CpuId = "0.3"
Distances = "0.10"
Distributions = "0.25"
FFTW = "1.5"
GeoStatsBase = "0.26"
KrigingEstimators = "0.9"
MLJModelInterface = "1.6"
Meshes = "0.23"
NearestNeighbors = "0.4"
SpecialFunctions = "2.1"
TableTransforms = "1.3"
Tables = "1.7"
Variography = "0.14"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
